# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trymulti.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDoubleValidator,QIntValidator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 921, 571))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_choose = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_choose.sizePolicy().hasHeightForWidth())
        self.frame_choose.setSizePolicy(sizePolicy)
        self.frame_choose.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choose.setObjectName("frame_choose")
        self.pushButton_switch_tri = QtWidgets.QPushButton(self.frame_choose)
        self.pushButton_switch_tri.setGeometry(QtCore.QRect(30, 90, 93, 28))
        self.pushButton_switch_tri.setObjectName("pushButton_switch_tri")
        self.pushButton_switch_cal = QtWidgets.QPushButton(self.frame_choose)
        self.pushButton_switch_cal.setGeometry(QtCore.QRect(30, 140, 93, 28))
        self.pushButton_switch_cal.setObjectName("pushButton_switch_cal")
        self.pushButton_switch_computersale = QtWidgets.QPushButton(self.frame_choose)
        self.pushButton_switch_computersale.setGeometry(QtCore.QRect(30, 190, 93, 28))
        self.pushButton_switch_computersale.setObjectName("pushButton_switch_computersale")
        self.pushButton_switch_charge = QtWidgets.QPushButton(self.frame_choose)
        self.pushButton_switch_charge.setGeometry(QtCore.QRect(30, 240, 93, 28))
        self.pushButton_switch_charge.setObjectName("pushButton_switch_charge")
        self.horizontalLayout.addWidget(self.frame_choose)
        self.frame_main = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main.sizePolicy().hasHeightForWidth())
        self.frame_main.setSizePolicy(sizePolicy)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_main)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 761, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")

        self.lineEdit_b = QtWidgets.QLineEdit(self.page)
        self.lineEdit_b.setGeometry(QtCore.QRect(290, 160, 151, 31))
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.label_tip = QtWidgets.QLabel(self.page)
        self.label_tip.setGeometry(QtCore.QRect(80, 70, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tip.setFont(font)
        self.label_tip.setObjectName("label_tip")
        self.label_title = QtWidgets.QLabel(self.page)
        self.label_title.setGeometry(QtCore.QRect(330, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.textBrowser_result = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_result.setGeometry(QtCore.QRect(260, 330, 221, 31))
        self.textBrowser_result.setObjectName("textBrowser_result")
        self.label_a = QtWidgets.QLabel(self.page)
        self.label_a.setGeometry(QtCore.QRect(240, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.label_b = QtWidgets.QLabel(self.page)
        self.label_b.setGeometry(QtCore.QRect(240, 160, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_b.setFont(font)
        self.label_b.setObjectName("label_b")
        self.label_c = QtWidgets.QLabel(self.page)
        self.label_c.setGeometry(QtCore.QRect(240, 210, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_c.setFont(font)
        self.label_c.setObjectName("label_c")
        self.submitButton_tri = QtWidgets.QPushButton(self.page)
        self.submitButton_tri.setGeometry(QtCore.QRect(280, 270, 71, 31))
        self.submitButton_tri.setObjectName("submitButton_tri")
        self.lineEdit_a = QtWidgets.QLineEdit(self.page)
        self.lineEdit_a.setGeometry(QtCore.QRect(290, 110, 151, 31))
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.lineEdit_c = QtWidgets.QLineEdit(self.page)
        self.lineEdit_c.setGeometry(QtCore.QRect(290, 210, 151, 31))
        self.lineEdit_c.setObjectName("lineEdit_c")
        self.label_result = QtWidgets.QLabel(self.page)
        self.label_result.setGeometry(QtCore.QRect(210, 340, 72, 15))
        self.label_result.setObjectName("label_result")
        self.clearButton_tri = QtWidgets.QPushButton(self.page)
        self.clearButton_tri.setGeometry(QtCore.QRect(380, 270, 71, 31))
        self.clearButton_tri.setObjectName("clearButton_tri")
        self.label_hint_tri_2 = QtWidgets.QLabel(self.page)
        self.label_hint_tri_2.setGeometry(QtCore.QRect(90, 410, 151, 31))
        self.label_hint_tri_2.setObjectName("label_hint_tri_2")
        self.comboBox_tri = QtWidgets.QComboBox(self.page)
        self.comboBox_tri.setGeometry(QtCore.QRect(260, 410, 181, 31))
        self.comboBox_tri.setObjectName("comboBox_tri")
        self.comboBox_tri.addItem("")
        self.comboBox_tri.addItem("")
        self.testButton_tri = QtWidgets.QPushButton(self.page)
        self.testButton_tri.setGeometry(QtCore.QRect(510, 410, 71, 31))
        self.testButton_tri.setObjectName("testButton_tri")
        self.tableWidget_tri = QtWidgets.QTableWidget(self.page)
        self.tableWidget_tri.setGeometry(QtCore.QRect(50, 30, 651, 481))
        self.tableWidget_tri.setObjectName("tableWidget_tri")
        self.tableWidget_tri.setColumnCount(0)
        self.tableWidget_tri.setRowCount(0)
        self.tableWidget_tri.hide()
        self.stackedWidget.addWidget(self.page)
        edge_constriant = QDoubleValidator()
        self.lineEdit_a.setValidator(edge_constriant)
        self.lineEdit_b.setValidator(edge_constriant)
        self.lineEdit_c.setValidator(edge_constriant)

        # page2
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_title_calendar = QtWidgets.QLabel(self.page_2)
        self.label_title_calendar.setGeometry(QtCore.QRect(320, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title_calendar.setFont(font)
        self.label_title_calendar.setObjectName("label_title_calendar")
        self.pushButton_submit_cal = QtWidgets.QPushButton(self.page_2)
        self.pushButton_submit_cal.setGeometry(QtCore.QRect(290, 310, 61, 31))
        self.pushButton_submit_cal.setObjectName("pushButton_submit_cal")
        self.lineEdit_day = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_day.setGeometry(QtCore.QRect(310, 240, 151, 31))
        self.lineEdit_day.setObjectName("lineEdit_day")
        self.label_hintcal = QtWidgets.QLabel(self.page_2)
        self.label_hintcal.setGeometry(QtCore.QRect(140, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_hintcal.setFont(font)
        self.label_hintcal.setObjectName("label_hintcal")
        self.label_month = QtWidgets.QLabel(self.page_2)
        self.label_month.setGeometry(QtCore.QRect(250, 180, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_month.setFont(font)
        self.label_month.setObjectName("label_month")
        self.pushButton_clear_cal = QtWidgets.QPushButton(self.page_2)
        self.pushButton_clear_cal.setGeometry(QtCore.QRect(390, 310, 61, 31))
        self.pushButton_clear_cal.setObjectName("pushButton_clear_cal")
        self.label_day = QtWidgets.QLabel(self.page_2)
        self.label_day.setGeometry(QtCore.QRect(260, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_day.setFont(font)
        self.label_day.setObjectName("label_day")
        self.label_year = QtWidgets.QLabel(self.page_2)
        self.label_year.setGeometry(QtCore.QRect(260, 130, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_year.setFont(font)
        self.label_year.setObjectName("label_year")
        self.lineEdit_year = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_year.setGeometry(QtCore.QRect(310, 140, 151, 31))
        self.lineEdit_year.setObjectName("lineEdit_year")
        self.lineEdit_month = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_month.setGeometry(QtCore.QRect(310, 190, 151, 31))
        self.lineEdit_month.setObjectName("lineEdit_month")
        self.textBrowser_result_cal = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_result_cal.setGeometry(QtCore.QRect(280, 360, 221, 31))
        self.textBrowser_result_cal.setObjectName("textBrowser_result_cal")
        self.testButton_cal = QtWidgets.QPushButton(self.page_2)
        self.testButton_cal.setGeometry(QtCore.QRect(530, 440, 71, 31))
        self.testButton_cal.setObjectName("testButton_cal")
        self.label_result_cal = QtWidgets.QLabel(self.page_2)
        self.label_result_cal.setGeometry(QtCore.QRect(230, 370, 72, 15))
        self.label_result_cal.setObjectName("label_result_cal")
        self.comboBox_cal = QtWidgets.QComboBox(self.page_2)
        self.comboBox_cal.setGeometry(QtCore.QRect(280, 440, 181, 31))
        self.comboBox_cal.setObjectName("comboBox_cal")
        self.comboBox_cal.addItem("")
        self.comboBox_cal.addItem("")
        self.label_hint_cal = QtWidgets.QLabel(self.page_2)
        self.label_hint_cal.setGeometry(QtCore.QRect(110, 440, 151, 31))
        self.label_hint_cal.setObjectName("label_hint_cal")
        self.tableWidget_cal = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_cal.setGeometry(QtCore.QRect(40, 30, 671, 481))
        self.tableWidget_cal.setObjectName("tableWidget_cal")
        self.tableWidget_cal.setColumnCount(0)
        self.tableWidget_cal.setRowCount(0)
        self.tableWidget_cal.hide()
        self.stackedWidget.addWidget(self.page_2)

        date_vali = QIntValidator()
        self.lineEdit_year.setValidator(date_vali)
        self.lineEdit_month.setValidator(date_vali)
        self.lineEdit_day.setValidator(date_vali)

        #page_3
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_title_sale = QtWidgets.QLabel(self.page_3)
        self.label_title_sale.setGeometry(QtCore.QRect(280, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title_sale.setFont(font)
        self.label_title_sale.setObjectName("label_title_sale")
        self.label_tip_sale = QtWidgets.QLabel(self.page_3)
        self.label_tip_sale.setGeometry(QtCore.QRect(60, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tip_sale.setFont(font)
        self.label_tip_sale.setObjectName("label_tip_sale")
        self.testButton_sale = QtWidgets.QPushButton(self.page_3)
        self.testButton_sale.setGeometry(QtCore.QRect(490, 430, 71, 31))
        self.testButton_sale.setObjectName("testButton_sale")
        self.textBrowser_result_sale = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_result_sale.setGeometry(QtCore.QRect(240, 350, 221, 31))
        self.textBrowser_result_sale.setObjectName("textBrowser_result_sale")
        self.lineEdit_peripheral = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_peripheral.setGeometry(QtCore.QRect(270, 230, 151, 31))
        self.lineEdit_peripheral.setObjectName("lineEdit_peripheral")
        self.label_result_sale = QtWidgets.QLabel(self.page_3)
        self.label_result_sale.setGeometry(QtCore.QRect(140, 355, 91, 21))
        self.label_result_sale.setObjectName("label_result_sale")
        self.clearButton_sale = QtWidgets.QPushButton(self.page_3)
        self.clearButton_sale.setGeometry(QtCore.QRect(360, 290, 71, 31))
        self.clearButton_sale.setObjectName("clearButton_sale")
        self.label_peripheral = QtWidgets.QLabel(self.page_3)
        self.label_peripheral.setGeometry(QtCore.QRect(200, 230, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_peripheral.setFont(font)
        self.label_peripheral.setObjectName("label_peripheral")
        self.lineEdit_display = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_display.setGeometry(QtCore.QRect(270, 180, 151, 31))
        self.lineEdit_display.setObjectName("lineEdit_display")
        self.comboBox_sale = QtWidgets.QComboBox(self.page_3)
        self.comboBox_sale.setGeometry(QtCore.QRect(240, 430, 181, 31))
        self.comboBox_sale.setObjectName("comboBox_sale")
        self.comboBox_sale.addItem("")
        self.comboBox_sale.addItem("")
        self.label_display = QtWidgets.QLabel(self.page_3)
        self.label_display.setGeometry(QtCore.QRect(190, 180, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_display.setFont(font)
        self.label_display.setObjectName("label_display")
        self.label_hint_sale_2 = QtWidgets.QLabel(self.page_3)
        self.label_hint_sale_2.setGeometry(QtCore.QRect(70, 430, 151, 31))
        self.label_hint_sale_2.setObjectName("label_hint_sale_2")
        self.lineEdit_host = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_host.setGeometry(QtCore.QRect(270, 130, 151, 31))
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.submitButton_sale = QtWidgets.QPushButton(self.page_3)
        self.submitButton_sale.setGeometry(QtCore.QRect(260, 290, 71, 31))
        self.submitButton_sale.setObjectName("submitButton_sale")
        self.label_host = QtWidgets.QLabel(self.page_3)
        self.label_host.setGeometry(QtCore.QRect(200, 130, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_host.setFont(font)
        self.label_host.setObjectName("label_host")
        self.tableWidget_sale = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_sale.setGeometry(QtCore.QRect(50, 20, 651, 491))
        self.tableWidget_sale.setObjectName("tableWidget_sale")
        self.tableWidget_sale.setColumnCount(0)
        self.tableWidget_sale.setRowCount(0)
        self.tableWidget_sale.hide()
        self.stackedWidget.addWidget(self.page_3)

        # 整数限制
        num_constriant = QIntValidator()
        self.lineEdit_host.setValidator(num_constriant)
        self.lineEdit_display.setValidator(num_constriant)
        self.lineEdit_peripheral.setValidator(num_constriant)


        # page4
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_title_charge = QtWidgets.QLabel(self.page_4)
        self.label_title_charge.setGeometry(QtCore.QRect(320, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title_charge.setFont(font)
        self.label_title_charge.setObjectName("label_title_charge")
        self.label_tip_charge = QtWidgets.QLabel(self.page_4)
        self.label_tip_charge.setGeometry(QtCore.QRect(40, 90, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tip_charge.setFont(font)
        self.label_tip_charge.setObjectName("label_tip_charge")
        self.label_totalcount = QtWidgets.QLabel(self.page_4)
        self.label_totalcount.setGeometry(QtCore.QRect(160, 210, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_totalcount.setFont(font)
        self.label_totalcount.setObjectName("label_totalcount")
        self.textBrowser_result_charge = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_result_charge.setGeometry(QtCore.QRect(280, 350, 221, 31))
        self.textBrowser_result_charge.setObjectName("textBrowser_result_charge")
        self.label_hint_charge = QtWidgets.QLabel(self.page_4)
        self.label_hint_charge.setGeometry(QtCore.QRect(110, 430, 151, 31))
        self.label_hint_charge.setObjectName("label_hint_charge")
        self.submitButton_charge = QtWidgets.QPushButton(self.page_4)
        self.submitButton_charge.setGeometry(QtCore.QRect(280, 270, 71, 31))
        self.submitButton_charge.setObjectName("submitButton_charge")
        self.lineEdit_totalTime = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_totalTime.setGeometry(QtCore.QRect(310, 160, 151, 31))
        self.lineEdit_totalTime.setObjectName("lineEdit_totalTime")
        self.comboBox_charge = QtWidgets.QComboBox(self.page_4)
        self.comboBox_charge.setGeometry(QtCore.QRect(280, 430, 181, 31))
        self.comboBox_charge.setObjectName("comboBox_charge")
        self.comboBox_charge.addItem("")
        self.comboBox_charge.addItem("")
        self.label_totalTime = QtWidgets.QLabel(self.page_4)
        self.label_totalTime.setGeometry(QtCore.QRect(170, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_totalTime.setFont(font)
        self.label_totalTime.setObjectName("label_totalTime")
        self.lineEdit_totalcount = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_totalcount.setGeometry(QtCore.QRect(310, 210, 151, 31))
        self.lineEdit_totalcount.setObjectName("lineEdit_totalcount")
        self.label_result_charge = QtWidgets.QLabel(self.page_4)
        self.label_result_charge.setGeometry(QtCore.QRect(180, 355, 91, 21))
        self.label_result_charge.setObjectName("label_result_charge")
        self.testButton_charge = QtWidgets.QPushButton(self.page_4)
        self.testButton_charge.setGeometry(QtCore.QRect(510, 430, 71, 31))
        self.testButton_charge.setObjectName("testButton_charge")
        self.clearButton_charge = QtWidgets.QPushButton(self.page_4)
        self.clearButton_charge.setGeometry(QtCore.QRect(400, 270, 71, 31))
        self.clearButton_charge.setObjectName("clearButton_charge")
        self.tableWidget_charge = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget_charge.setGeometry(QtCore.QRect(30, 30, 681, 501))
        self.tableWidget_charge.setObjectName("tableWidget_charge")
        self.tableWidget_charge.setColumnCount(0)
        self.tableWidget_charge.setRowCount(0)
        self.tableWidget_charge.hide()
        self.stackedWidget.addWidget(self.page_4)

        charge_constraint = QIntValidator()
        self.lineEdit_totalTime.setValidator(charge_constraint)
        self.lineEdit_totalcount.setValidator(charge_constraint)

        self.horizontalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_switch_tri.setText(_translate("MainWindow", "三角形"))
        self.pushButton_switch_cal.setText(_translate("MainWindow", "万年历"))
        self.pushButton_switch_computersale.setText(_translate("MainWindow", "电脑销售"))
        self.pushButton_switch_charge.setText(_translate("MainWindow", "电信收费"))
        self.label_tip.setText(_translate("MainWindow", "请输入三角形的边长:"))
        self.label_title.setText(_translate("MainWindow", "三角形问题"))
        self.label_a.setText(_translate("MainWindow", "a:"))
        self.label_b.setText(_translate("MainWindow", "b:"))
        self.label_c.setText(_translate("MainWindow", "c:"))
        self.submitButton_tri.setText(_translate("MainWindow", "提交"))
        self.label_result.setText(_translate("MainWindow", "结果:"))
        self.clearButton_tri.setText(_translate("MainWindow", "清空"))
        self.label_hint_tri_2.setText(_translate("MainWindow", "通过csv文件进行测试"))
        self.comboBox_tri.setItemText(0, _translate("MainWindow", "边界值法"))
        self.comboBox_tri.setItemText(1, _translate("MainWindow", "等价类法"))
        self.testButton_tri.setText(_translate("MainWindow", "测试"))
        self.label_title_calendar.setText(_translate("MainWindow", "万年历问题"))
        self.pushButton_submit_cal.setText(_translate("MainWindow", "提交"))
        self.label_hintcal.setText(_translate("MainWindow", "请输入年月日:"))
        self.label_month.setText(_translate("MainWindow", "month"))
        self.pushButton_clear_cal.setText(_translate("MainWindow", "清空"))
        self.label_day.setText(_translate("MainWindow", "day"))
        self.label_year.setText(_translate("MainWindow", "year"))
        self.testButton_cal.setText(_translate("MainWindow", "测试"))
        self.label_result_cal.setText(_translate("MainWindow", "结果:"))
        self.comboBox_cal.setItemText(0, _translate("MainWindow", "边界值法"))
        self.comboBox_cal.setItemText(1, _translate("MainWindow", "等价类法"))
        self.label_hint_cal.setText(_translate("MainWindow", "通过csv文件进行测试"))
        self.label_title_sale.setText(_translate("MainWindow", "电脑销售问题"))
        self.label_tip_sale.setText(_translate("MainWindow", "请输入各部件销售数量:"))
        self.testButton_sale.setText(_translate("MainWindow", "测试"))
        self.label_result_sale.setText(_translate("MainWindow", "本月销售额:"))
        self.clearButton_sale.setText(_translate("MainWindow", "清空"))
        self.label_peripheral.setText(_translate("MainWindow", "外设"))
        self.comboBox_sale.setItemText(0, _translate("MainWindow", "边界值法"))
        self.comboBox_sale.setItemText(1, _translate("MainWindow", "等价类法"))
        self.label_display.setText(_translate("MainWindow", "显示器"))
        self.label_hint_sale_2.setText(_translate("MainWindow", "通过csv文件进行测试"))
        self.submitButton_sale.setText(_translate("MainWindow", "提交"))
        self.label_host.setText(_translate("MainWindow", "主机:"))
        self.label_title_charge.setText(_translate("MainWindow", "电信收费问题"))
        self.label_tip_charge.setText(_translate("MainWindow", "请输入总计通话时间与年度迟交次数:"))
        self.label_totalcount.setText(_translate("MainWindow", "年度迟交次数"))
        self.label_hint_charge.setText(_translate("MainWindow", "通过csv文件进行测试"))
        self.submitButton_charge.setText(_translate("MainWindow", "提交"))
        self.comboBox_charge.setItemText(0, _translate("MainWindow", "边界值法"))
        self.comboBox_charge.setItemText(1, _translate("MainWindow", "等价类法"))
        self.label_totalTime.setText(_translate("MainWindow", "总通话时间"))
        self.label_result_charge.setText(_translate("MainWindow", "应收费用："))
        self.testButton_charge.setText(_translate("MainWindow", "测试"))
        self.clearButton_charge.setText(_translate("MainWindow", "清空"))

